## 1.b
First lets define our matrix:

In [29]:
import numpy as np
from scipy import linalg 

A = np.mat('[1 2 3 4;2 4 -4 8;-5 4 1 5;5 0 -3 -7]')

Calculating A*A

In [31]:
A_t_A = A.T.dot(A)

Find eigen vectors, and calculate the square of each eigenvalue

In [42]:
vals, vecs = linalg.eig(A_t_A)
squared_vals = np.sqrt(vals)

<p> Now we will take the vector corresponding to the largest eigenvalue (absolutly) multiply it with A and calculate the l2 norm of the result. </p>
<em>We dont need to devide by |x| because scipy provided orthonormal eigenvectors</em>

In [48]:
linalg.norm(A.dot(vecs[:,0]))

13.858100376465325

This is essentialy the same as:

In [47]:
squared_vals[0]

(13.858100376465332+0j)

# 4.a
First lets define our matrix:

In [67]:
A = np.mat('[2 1 2;1 -2 1;1 2 3;1 1 1]')
b = np.array([[6],[1],[5],[2]])


Use cholescy to decompose matrix A^TA to R* (lower triangle) and R (upper triangle)

In [72]:
R = linalg.cholesky(A.T.dot(A))
R_star = R.T 

By definition of cholesky decomposition R got positive diagonal, so its full rank and invertible. 
We can invert the matrix or use scipy solve_triangular

In [79]:
R_x = linalg.solve_triangular(R_star,A.T.dot(b), lower=True)
x = linalg.solve_triangular(R,R_x)
x

array([[1.7],
       [0.6],
       [0.7]])

# 4.b

We know that QR factorization of $A$ leads us to:
$$x = (R^TQ^TQR)^-\cdot R^T\cdot Q^T\cdot b$$
$$x = R^-\cdot Q^T\cdot b$$

In [86]:
q, r = linalg.qr(A, mode='economic')
x = linalg.inv(r).dot(q.T).dot(b)
x

array([[1.7],
       [0.6],
       [0.7]])

We indeed recived the same answer!

## Using SVD

In [100]:
u, diag, v_t = linalg.svd(A, full_matrices=False)

based on the lecture by decomposing A with svd the normal equation is: 
$\Sigma \cdot V^T \cdot \hat{x}= U^T b$ <br>
We set $y=V^T \cdot \hat{x}$

In [101]:
# np.diag(diag) turns diag into an actual diagonal matrix
y = linalg.solve_triangular(np.diag(diag),u.T.dot(b))

In [106]:
x = linalg.inv(v_t).dot(y)
x

array([[1.7],
       [0.6],
       [0.7]])

# 4.c

In [111]:
r = A.dot(x) - b
r

matrix([[-6.0000000e-01],
        [ 2.0000000e-01],
        [ 8.8817842e-16],
        [ 1.0000000e+00]])

In [112]:
A.T.dot(r)

matrix([[-2.88657986e-15],
        [-4.44089210e-16],
        [-1.11022302e-15]])

$A^Tr = A^T Ax - A^Tb$ which is the left side of the normal equation (when compared to zero). The normal equation is infact the derivitive of the LS. When we solve LS we try to find $x$ s.t the derivitive is zero. We had already proven that the normal equation got a solution so its obvius that if we had found some $x$ that satisfies the equation, once we use it we will get zero.

# 4.d
We will set vector $w$ to be diagonal matrix of ones and $10^3$ in the upper left corner

In [120]:
w= np.identity(4)
w[0,0] = 10**3
w

array([[1000.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.],
       [   0.,    0.,    1.,    0.],
       [   0.,    0.,    0.,    1.]])

We will use cholesky decomposition, similar to 4.a

In [133]:
R = linalg.cholesky(A.T.dot(w).dot(A))
R_star = R.T 
# solve equations represented by triangular matrix
R_x = linalg.solve_triangular(R_star,A.T.dot(w).dot(b), lower=True)
x = linalg.solve_triangular(R,R_x)
x

array([[2.17244031],
       [0.69218347],
       [0.48106425]])

In [131]:
r = A.dot(x) - b
r

matrix([[-8.07412819e-04],
        [ 2.69137606e-01],
        [ 6.03961325e-13],
        [ 1.34568803e+00]])

we can see that indeed the firs coordinate is $10^3$ times smaller (absolutly) then the previous answer